name: Find flag code references

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Type of environment to provision (eap or production)"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  find-code-references:
    name: Find code references
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 3 # used with lookback for extinctions
      - name: Find code refereneces
        uses: launchdarkly/find-code-references@v2
        with:
          accessToken: ${{ secrets.LD_API_KEY }}
          baseUri: https://ld-stg.launchdarkly.com
          contextLines: 5
          debug: true
          ignoreServiceErrors: true
          projKey: default # may omit if repo has projects configured in config file. See https://github.com/launchdarkly/ld-find-code-refs/blob/main/docs/CONFIGURATION.md#yaml
