name: Manually Add Code References to LaunchDarkly Project

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Type of environment to provision (eap or production)"
        required: true

env:
  LD_API_KEY: ${secrets.LD_API_KEY}
  LD_PROJECT_KEY: ${secrets.LD_PROJECT_KEY}

jobs:
  add-code-references:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 11

      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v2.12.0
        with:
          accessToken: ${{ env.LD_API_KEY }}
          projKey: ${{ env.LD_PROJECT_KEY }}
          repoName: main
